### ISSUE TITLE
{ purge: true } option of Actor.main deletes all local storages

### ISSUE THREAD

**Issue by AndreyBykov** [apify/apify-ts#102]
**Describe the bug**
`{ purge: true }` option should mimic `-p` param of `apify run`, i.e. it should remove default storages besides `INPUT.json` file in default key-value store. Instead - it removes all storage (default and non-default) and all files.

**To Reproduce**
Run any actor with `{ purge: true }` param and some `INPUT.json` file or any non-default storage folder on disk.

**Expected behavior**
Only default storages should be cleared. `INPUT.json` in default key-value store should stay in place.

**System information:**
 - OS: MacOS 12.3.1
 - Node.js version: 16.14.0
 - Apify SDK version: 3.0.0-alpha.22

**Comment by B4nan** [comment]
Please look into this yourself, you know best how the purge flag behaves in CLI :]
