### ISSUE TITLE
Update dependencies in all packages

### ISSUE THREAD

**Issue by AndreyBykov** [apify/apify-ts#114]
We should go through all the packages and make sure that there are no undeclared dependencies, e.g. `@crawlee/puppeteer` has `@crawlee/browser-pool`, `ow`, `@apify/datastructures` and some others not present in `package.json`.

**Comment by B4nan** [comment]
I fixed all the issues that were causing build failures already, we still need to go thru all the deps anyway, there will be some missing (just not breaking the build) most probably.

**Comment by B4nan** [comment]
Also fixed the missing jquery in PW crawler package. All basic crawlee templates seems to be working fine both locally and on platform finally.
