### ISSUE TITLE
got-scraping guide

### ISSUE THREAD

**Issue by szmarczak** [apify/apify-ts#167]
we should have this documented elsewhere too, maybe a separate guide mentioning how to work with gotScraping, `sendRequest` helper would be one section there. then the upgrading guide could just link it, right now it feels like this change takes quite a substantial space on the upgrading guide :]

_Originally posted by @B4nan in https://github.com/apify/apify-ts/pull/166#discussion_r912985575_

**Comment by B4nan** [comment]
I was hoping to see this being done later this week, offloading comments to new issues is fine, but please take care of them with priority.
