### ISSUE TITLE
CRAWLEE_LOG_LEVEL env var not supported

### ISSUE THREAD

**Issue by AndreyBykov** [apify/apify-ts#171]
**Describe the bug**
`APIFY_` vs `CRAWLEE_` env vars:
if I set `process.env.CRAWLEE_LOG_LEVEL` locally to DEBUG - it would not show debug messages. With `log.setLevel(log.LEVELS.DEBUG)` it works as expected.

From @B4nan:

> I guess that's because this is implemented in the logger directly. I guess we should set the log level when bootstrapping the Configuration class, definitely worth supporting CRAWLEE_LOG_LEVEL.

**To Reproduce**
```
process.env.CRAWLEE_LOG_LEVEL = 'DEBUG';
log.debug('Test')
```

**Expected behavior**
Should log `Test` debug message to console.

**System information:**
 - OS: MacOS
 - Node.js version: 18
 - Crwalee version: 3.0.0-beta.67

**Comment by AndreyBykov** [comment]
Also probably should be added to env vars guide.

**Comment by B4nan** [comment]
Please update the guides
