### ISSUE TITLE
Move apify-storage-local-js to monorepo

### ISSUE THREAD

**Issue by B4nan** [apify/apify-ts#31]

**Comment by AndreyBykov** [comment]
Implemented via https://github.com/apify/apify-ts/pull/39

**Comment by B4nan** [comment]
next time add "closes #..." to the commit message or PR description and it will be done automatically :]

(does not matter much now, but once we start generating changelogs from commit messages, it will be important so we have the reference to given issue in the changelog)

**Comment by AndreyBykov** [comment]
yep, I know about it - yesterday I remembered about it while already falling asleep, so was going to add it today, and well - completely forgot in the morning :)
