### ISSUE TITLE
Rename `handlePageFunction` to `requestHandler`

### ISSUE THREAD

**Issue by B4nan** [apify/apify-ts#33]
Instead of `handlePageFunction` and `handleRequestFunction` we wil lhave `requestHandler`, instead of `handleFailedRequestFunction` there will be `failedRequestHandler`. 

We should keep the old options there to throw an exception saying that the method name changed. Should be marked as `@deprecated` in the interfaces. 

This applies to all related `handlePage*` options and class properties, e.g. `handlePageTimeoutSecs`.

**Comment by szmarczak** [comment]
Do we really want to do this? This can be confusing as `request` implies all requests, but I'm assuming it's not applicable when redirecting?

**Comment by B4nan** [comment]
I guess it will be still much less confusing than seeing errors about `handleRequestFunction` when you don't define one (but it will be used under the hood anyway). The goal here is to align behaviour/naming between the various levels of crawler classes. 

Request is what you add to the queue and what gets handled, redirects are followed by default, is this really a problem? Would you expect such handler to be executed for each redirect too? Is there a use case for this? Maybe we could have some way to configure handling redirects too, but it sounds like something that should just work.

**Comment by szmarczak** [comment]
I just got confused as I thought it would be closely related to HTTP requests. I'm good with this if it's documented properly :+1:
