### ISSUE TITLE
Remove `PseudoUrl` in favour of glob patterns

### ISSUE THREAD

**Issue by B4nan** [apify/apify-ts#45]
- move `PseudoUrl` implementation to new package in apify-shared-js
  - add also `purlToRegExp(purl: string): RegExp` function that will convert string pseudo url to regexp instance
- use this package in `enqueueLinks` (via `purlToRegExp` function), mark its usage as deprecated and suggets using `globs` instead
- allow using glob patterns (via [minimatch](https://github.com/isaacs/minimatch)) and regexes directly

```ts
enqueueLinks({
    globs: [
        'https://example.com/**',
        'https://example.com/?*/?*',
    ],
});

// or

enqueueLinks({
    regexps: [
        /https:\/\/example\.com.*/,
        /https:\/\/example\.com\/.+\/.+/,
    ],
});

// or

enqueueLinks({
    pseudoUrls: [
        'https://example.com/*',
        'https://example.com/*/*',
    ],
}),
```

In future (v4) we will remove the `pseudoUrls` usage and allow only explict `purlToRegExp` via `regexps`

**Comment by AndreyBykov** [comment]
Partially solved by https://github.com/apify/apify-shared-js/pull/288
