### ISSUE TITLE
Add `Actor.reboot()` to restart the container on the Apify platform

### ISSUE THREAD

**Issue by mnmkng** [apify/apify-ts#65]
Sometimes actors running on the Apify platform get into a state that they cannot easily recover from, like a memory leak. This can easily be fixed by aborting and resurrecting the actor, but that needs to be done manually. By adding `Actor.reboot()` we could enable this functionality from code.

The function should:
1. pause any running crawlers (it needs to accept those in options)
2. persist state (optionally, default true)
3. metamorph the actor into itself; this will restart the container while keeping the same `runId`, storages etc.

**Comment by barjin** [comment]
Initial implementation draft [is here](https://github.com/barjin/apify-ts/commit/8460dad35298338fed178f428094b73c9a42fce4).

Few questions/points to consider:
- Is passing the crawlers necessary? Making the user to name all their used crawlers sounds human-error-prone :) 
It seems to me that in cooperation with `RequestQueue`/`RequestList`, the consistency is ensured at all times (even with killing the crawlers' processes). Local tests (though very simple ones) do not show any problems either.

- NOT persisting the state effectively means purging all the run artifacts (output data, request queue...)?
I think this might be a problem with named datasets + KVS, as there is AFAIK no way to access those.

**Comment by mnmkng** [comment]
> Is passing the crawlers necessary? 

You need to [pause the crawlers](https://sdk.apify.com/docs/api/autoscaled-pool#autoscaledpoolpausetimeoutsecs) so that they can gracefully finish all pending operations. BasicCrawler does that automatically when it receives a migrating or abort signal, so technically, you could fake this signal, instead of pausing each crawler manually.

https://github.com/apify/apify-ts/blob/c3850ecdb8024cd9e7e80dbcde97a47a39121968/packages/basic-crawler/src/internals/basic-crawler.ts#L597-L609

> NOT persisting the state effectively means purging all the run artifacts (output data, request queue...)?

There are other things like the request list that need persisting.

https://github.com/apify/apify-ts/blob/c3850ecdb8024cd9e7e80dbcde97a47a39121968/packages/basic-crawler/src/internals/basic-crawler.ts#L611-L626

Thinking about it. Force emitting the abort signal might probably be the best choice, because all this will be handled automatically and we won't have duplicate code.

**Comment by barjin** [comment]
> Migration/Abort signals

Great point, sounds only reasonable 👍🏽 

> There are other things like the request list that need persisting.

Understood. The `persistState` event is emitted [regularly in intervals](https://github.com/apify/apify-ts/blob/c3850ecdb8024cd9e7e80dbcde97a47a39121968/packages/core/src/events.ts#L82), letting the persistable components know it's time to save their state. 

Emitting this event one more time before the reboot sounds like the only sensible choice here (otherwise, the state after reboot would be anything between 0 and 59 seconds old). What would the `persistState` option from the original issue toggle? It would make some sense to me to have a `purge` (or `dontPersistState` :) ) option, telling the actor to reboot the run with clean slate.

**Comment by mnmkng** [comment]
I wouldn't worry about the purge option. You would also have to remove all the items from the request queue, key value store and so on. Most of the actor's state is persisted all the time, because we use persistent storages. Only some things like the request list or session pool use the regular persisting interval. So when I talked about persisting, I really meant only making sure that those things get a chance to save, and also that any running tasks have a chance to finish - so that their status can get updated in RQ/KVS/Dataset and we won't get duplicate results.
